### ISSUE TITLE
Доступность меню на маленьких экранах

### ISSUE THREAD

**Issue by kolumb** [antonmaischeff/antonmaischeff.github.io#2]
Когда я увеличил масштаб страницы, пункты меню в диве пропали и стали совсем недоступны. 
Видимо из-за `        <div class="navbar-collapse collapse">`
Ты планируешь сделать гамбургер-меню, как все делали последние пару лет?

**Comment by kolumb** [comment]
Хотя теперь меню на планшетах перекрывает контент. Может все же добавить кнопку гамбургер на маленьких экранах, при нажатии на которую будет переключаться наличие классов `navbar-collapse collapse`?

**Comment by antonmaischeff** [comment]
я только позавчера разобрался с collapse(вернее понял, что оно делает)) в ближайшее время сделаю как надо
